#############################################################################
# A KIND development cluster with two worker nodes and a single control plane
#############################################################################
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: curitydemo
featureGates:
  EnvFiles: true
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ./containerd.service
    containerPath: /etc/systemd/system/containerd.service
- role: worker
  extraMounts:
  - hostPath: ./containerd.service
    containerPath: /etc/systemd/system/containerd.service
